name: branch

on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ develop ]
env:
  DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Release
      run: swift build -c release

    - name: Test CLI Package
      run: swift test

    - name: Test VariantsCore
      run: xcodebuild test -target VariantsCore -scheme VariantsCore
