name: "Close issue"

on:
  project_card:
    types: [moved]
    
jobs:
  close-issue:
    name: "Close issue when card moves to Done column"
    runs-on: ubuntu-latest
    steps:
      - name: Close issue
        run: |
          echo "Column name ${{ github.event.project_card.id }}"
