name: "Danger Swift"

on:
  pull_request:
    types: [ opened, synchronize ]
    paths:
      - '**/*.swift'

jobs:
  danger-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Danger
        uses: danger/swift@3.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
