name: develop

on:
  push:
    branches: [ develop ]
env:
  DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test CLI Package
      run: swift test -v

    - name: Test VariantsCore
      run: xcodebuild test -scheme VariantsCoreTests
